import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import StateProviders from '@components/Providers/StateProviders';
import { GeistSans } from 'geist/font/sans';
import '@styles/main.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get('theme')?.value ?? 'dark';

  return (
    <html lang="en" className={GeistSans.className} data-theme={theme}>
      <StateProviders theme={theme}>{children}</StateProviders>
    </html>
  );
}
