import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import ThemeProvider from '@components/ThemeProvider';
import ToastProvider from '@components/ToastProvider';
import { GeistSans } from 'geist/font/sans';
import '@/styles/main.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get('theme')?.value ?? 'dark';

  return (
    <html lang="en" className={GeistSans.className}>
      <ThemeProvider theme={theme}>
        <ToastProvider>{children}</ToastProvider>
      </ThemeProvider>
    </html>
  );
}
